#!/bin/bash
# config values
# copyright quodatum
# author: andy bunce
# license: apache 2
#
set -a 

BASEX_VERSION="http://files.basex.org/releases/7.9/BaseX79.zip"

#account
U="admin"
P="admin"

# ports, allowed values 15000->?
PORT_DATABASE= "15005" # database server
PORT_EVENT= "15006" # event server
PORT_STOP= "15007" # stop