#!/bin/bash
# config values
# copyright quodatum
# author: andy bunce
#

BASEX_VERSION="http://files.basex.org/releases/7.9/BaseX79.zip"
U=admin
P=admin
p= 15005 # database server
e= 15006 # event server
s= 15007 # stop