#!/bin/bash
# start BaseX http server, installing if required
# copyright quodatum
# author: andy bunce
#

# config
source config

# install basex if not installed or different version
cd $OPENSHIFT_DATA_DIR
if [ -d "basex" ] && [ "`cat basex/VERSION`" == $BASEX_VERSION ]; then
	echo "BaseX $BASEX_VERSION already installed"
else
	echo "Installing BaseX ${BASEX_VERSION}"
	if [ -d "basex" ]; then
		rm -rf basex
  	fi
	wget ${BASEX_VERSION}
	unzip *.zip
	rm *.zip
	echo $BASEX_VERSION > basex/VERSION
fi

# overlay app
echo "Overlaying app"
cp -rv ${OPENSHIFT_REPO_DIR}basex/ ${OPENSHIFT_DATA_DIR}

# run
cd $OPENSHIFT_DATA_DIR
nohup $OPENSHIFT_DATA_DIR/basex/bin/basexhttp \
                    -X -Dorg.basex.SERVERHOST=$OPENSHIFT_DIY_IP \
                    -X -Dorg.basex.SERVERPORT=$OPENSHIFT_DIY_PORT \
                    -p $p -e $e -s $s -U $U -P $P \
                    > ${OPENSHIFT_LOG_DIR}basex.log 2>&1 &