#!/bin/bash
# start BaseX http server, installing if required
# copyright quodatum
# author: andy bunce
# licence apache 2


# config
source ${OPENSHIFT_REPO_DIR}/config

# install basex if not installed or different version
cd $OPENSHIFT_DATA_DIR
if [ -d "basex" ] && [ "`cat basex/VERSION`" == $BASEX_VERSION ]; then
	echo "BaseX $BASEX_VERSION already installed"
else
	echo "Installing BaseX ${BASEX_VERSION}"
	if [ -d "basex" ]; then
		rm -rf basex
  	fi
	wget ${BASEX_VERSION}
	unzip *.zip
	rm *.zip
	echo $BASEX_VERSION > basex/VERSION
fi

# overlay app
if [ -f ${OPENSHIFT_DATA_DIR}/basex/.basex ]; then
   echo "already overlay"
 else 
    echo "Overlaying app"
    cp -rv ${OPENSHIFT_REPO_DIR}basex/ ${OPENSHIFT_DATA_DIR}
fi

# run
cd $OPENSHIFT_DATA_DIR
nohup ${OPENSHIFT_DATA_DIR}/basex/bin/basexhttp -d \
                    -n ${OPENSHIFT_DIY_IP} -h ${OPENSHIFT_DIY_PORT} \
                    -p ${PORT_DATABASE} -s ${PORT_STOP} \
                    -U ${BASEX_USER} -P ${BASEX_PASSWORD} \
                     &