#!/bin/bash
# Stop BaseX http server
# copyright quodatum
# author: andy bunce
# licence apache 2

# hack around basexhttp stop issue
pkill java
exit

# see https://mailman.uni-konstanz.de/pipermail/basex-talk/2016-January/010004.html
# config
source ${OPENSHIFT_REPO_DIR}/config

cd $OPENSHIFT_DATA_DIR
${OPENSHIFT_DATA_DIR}/basex/bin/basexhttp \
                    -n ${OPENSHIFT_DIY_IP} -h ${OPENSHIFT_DIY_PORT} \
                    -p ${PORT_DATABASE} -s ${PORT_STOP} \
                     stop 
