#!/bin/bash
# Stop BaseX http server
# copyright quodatum
# author: andy bunce
# licence apache 2

# config
source config

$OPENSHIFT_DATA_DIR/basex/bin/basexhttpstop \
                    -p ${PORT_DATABASE} -e ${PORT_EVENT} -s ${PORT_STOP} \
                    > ${OPENSHIFT_LOG_DIR}basex.log 2>&1 &