#!/bin/bash
# config values
# copyright quodatum
# author: andy bunce
# license: apache 2
#
set -a 

# path to zip distribution for required basex version
#BASEX_VERSION="http://files.basex.org/releases/7.9/BaseX79.zip"
BASEX_VERSION=https://github.com/Quodatum/openshift-basex-quick-start/releases/download/v0.3-alpha/BaseX80-20150106.134426.zip

#account
BASEX_USER="admin"
BASEX_PASSWORD="admin"

# ports, allowed values 15000 - 16000
PORT_DATABASE="15005" 
PORT_EVENT="15006" 
PORT_STOP="15007"
 