#!/bin/bash
# config values to setup basex
# copyright quodatum
# author: andy bunce
# license: apache 2
#
set -a 

# path to zip distribution for required basex version
BASEX_VERSION="http://files.basex.org/releases/8.0.1/BaseX801.zip"

#account
BASEX_USER="admin"
BASEX_PASSWORD="admin"

# ports, allowed values 15000 - 16000
PORT_DATABASE="15005" 
PORT_EVENT="15006" 
PORT_STOP="15007"
 